### ISSUE TITLE
Day 9: Advanced Visualization with Seaborn

### ISSUE THREAD

**Issue by Thedla** [Thedla/ML_Learning_Roadmap#10]
### Topics:

- [ ] Statistical plots: histograms, box plots, violin plots.
- [ ] Pair plots and correlation heatmaps.

### Tasks:

- [ ] Visualize the distribution of passenger age using a histogram.
- [ ] Create a heatmap to explore correlations between variables (age, fare, etc.).

### Resources:

- Seaborn Documentation
